### ISSUE TITLE
Reddit config file is missing a LINE separator

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#115]
### Describe the bug
Reddit text copy button spacing error

### To Reproduce
**Version**: 2.0.0.1
**Steps to reproduce the behavior**:
1. Right click on Reddit button for either Buy at or Sell at button
2. Paste into a text editor
3. See spacing between Landing Pad and Star Distance

### Expected behavior
need a space between landing pad data and star distance

### Screenshots

CARRIER UNLOADING JOB - SILVER - 20KCR/T

Type: Unloading
System: Mandhrithar
Carrier: [Your carrier name goes here]
Station: O'Leary City
Commodity: Silver
Profit: 20kcr/t
Supply: 20k
Station buy Price: 326204cr
Carrier selling at: 306204cr
Landing Pad: LStar Distance: 1123.0Ls  <<------

CARRIER LOADING JOB - SILVER - 20KCR/T

Type: Loading
System: Gliese 868
Carrier: [Your carrier name goes here]
Station: MacLean Terminal
Commodity: Silver
Profit: 20kcr/t
Demand: 20k
Station sell Price: 33961cr
Carrier buying at: 53961cr
Landing Pad: LStar Distance: 36.0Ls  <<------
### Additional context
...

**Comment by Fi0x** [comment]
Thanks for your quick bug-reporting!

I'll add a fix in the next update, but if you wan't to fix it right now on your own installation, you can go to the settings and click the `Open Reddit Config`-Button. In the json-file that should open, you only need to add a "LINE" between "+Pad" and "+Star_Distance+" like in the picture:
![image](https://user-images.githubusercontent.com/58072122/205121961-5bd00dee-af0e-44b6-b2dd-f5254ac20a9a.png)

You can also use this config file to change the general structure of the text you get from clicking the `Reddig`-Button

**Comment by msteele999** [comment]
Cool - I'll fix it here locally.

Now my profits are so much lower :-(  LOL

**Comment by Fi0x** [comment]
Better to be realistic than to make false hopes ;)
Just wait for the next big trade-based community goal and you'll see some green numbers again ;)

**Comment by msteele999** [comment]
Manually added in the reddit config file
