### ISSUE TITLE
Add Carrier Name field to settings for inclusion in the Reddit text creation button

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#116]
### Is your feature request related to a problem? Please describe.
Feature Request

### Describe the solution you'd like
Allow adding Carrier Name field to settings so it can be included in the Reddit text creation button results

### Describe alternatives you've considered
Doing it manually :-)

### Additional context
...

**Comment by Fi0x** [comment]
Adding your carrier name is currently done in the reddit-config-file.

You can reach it by Settings>Open Reddit Config
In the 6th line is the text `"CARRIER": "Carrier: [Your carrier name goes here]"`. Just replace the `[Your carrier name goes here]` part with your custom name and save the file.

[This wiki-page](https://github.com/Fi0x/EDCT/wiki/Reddit-config) contains more information on how you can configure this config-file.

**Comment by msteele999** [comment]
Manually added in the Reddit config file!

**Comment by Fi0x** [comment]
Added in v2.1.1.0 (in the settings)
