### ISSUE TITLE
UI very slow after changing filters

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#119]
### Describe the bug
After making changes to the Min. Quantity or the Min gal.Avg. fields, the application slows to a crawl. Clicking buttons (Next Commodity, Previous Commodity, etc.) take up to five seconds to process.

### To Reproduce
**Version**: 2.1.0.0 .exe version
**Steps to reproduce the behavior**:
1. Open up the app
2. highlight the Min Quantity field
3. begin typing a new quantity
4. observe that it takes seconds for the input to register in the text field

### Expected behavior
Instantaneous response to keyboard input

### Additional context
Closing the app and restarting it resolves it temporarily

**Comment by Fi0x** [comment]
While you're typing, the tool constantly updates the trades for each input change. That's why typing seems so slow.

Is the tool still slow after you stopped typing? Or are the 'next' and 'previous' buttons as fast as before?

**Comment by msteele999** [comment]
it's still slow after typing has been completed.

I wonder if putting a pause in to see if the field is going to have more
information would help with this

**Comment by Fi0x** [comment]
In v2.1.1.0 the update now only occurs once you press enter.

If your typing-lag occurs again, please re-open this issue or create a new one to let me know
