### ISSUE TITLE
Ability to manually select a commodity

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#122]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
The option to select a commodity from a pull down / check box screen. Paging thru using Next / Previous is good for viewing by highest to lowest profit, however it would be useful to be able to go right to a Commodity that you know you want to buy / sell

### Describe alternatives you've considered
None - just using Inara if necessary.

### Additional context
...

**Comment by Fi0x** [comment]
Your alternative solution is exactly why the tool is missing this feature. The main goal of this tool is to find the best fleet carrier trades, not to allow the user to search manually for good prices. Since you can search specific commodities on inara, this feature won't be implemented for now.

**Comment by msteele999** [comment]
understood - thank you for answering all my questions.

I hope it is not becoming a burden. I guess I know less than I thought I
did about Elite Trading :-)

**Comment by Fi0x** [comment]
Don't worry about bothering me, I'm always happy to help.
And I prefer to have a few more feature requests and bug reports, than people who stop using the tool because of a bug they won't report.
