### ISSUE TITLE
Date / Time stamp showing the last update 

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#123]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
When looking at the screen, I am not clear on when the last update occurred or how many records were updated / sync'd. It would be nice to have a mini dashboard showing that info - maybe as a popup or maybe on the same location as the local data age. I sync every 5 minutes - but I'm not clear on how many records that includes.  The local data age was confusing me for this until I looked at the tool tip :-)

### Describe alternatives you've considered
...

### Additional context
...

**Comment by Fi0x** [comment]
I will see what I can do to clarify some values and make more data visible without overloading the UI

**Comment by Fi0x** [comment]
Clicking on the data-age label will now display a popup with information about your local database:
![image](https://user-images.githubusercontent.com/58072122/206176358-59781460-700a-4d9d-a887-a4718407cfd6.png)

Implemented in v2.2.0.0
