### ISSUE TITLE
Demand Tonnage not equal to or greater than Min Quantity setting

### ISSUE THREAD

**Issue by msteele999** [Fi0x/EDCT#124]
### Describe the bug
See screen shot - Sell at location has a Demand amount of 2 tons, Min Quantity is 20,000 tons.

### To Reproduce
**Version**: 2.1.1.0
**Steps to reproduce the behavior**:
1. Set Min quantity to 20,000
2. Reload Trades
3. Scroll thru Next Station and observe Demand amounts

### Expected behavior
Only stations with a demand greater than or equal to the Min Quantity would display in Sell At window.

**_If this is by design (meaning a partial sale of the entire cargo amount) then please disregard, or change this to a feature request - perhaps a check box "Sell At QTY must equal Min. Quantity Amount" or "Allow partial quantity for Sell At Station"_**

### Screenshots

![Snag_943f36b](https://user-images.githubusercontent.com/6474337/205465714-09e2c593-0133-45ce-90cd-9b502161595a.png)

### Additional context
...

**Comment by Fi0x** [comment]
That is intended, because the station will buy your commodities even if it has 0 demand.
There is a checkbox in the filters where you can decide to display or ignore 0 demand stations.

**Comment by msteele999** [comment]
I was aware of the zero listing meaning unlimited demand. I was not aware that a station would purchase more than it's demand - meaning if the station demand is 100 and I arrive with 700 they will buy them all.

**Comment by Fi0x** [comment]
That is exactly the case and why I added the checkbox.
The only risk you have with a 0 demand station is a higher price fluctuation during your unload-process
