### ISSUE TITLE
Error 429 while starting up

### ISSUE THREAD

**Issue by rucomania** [Fi0x/EDCT#139]
### Describe the bug
When i startup the app after about 40/166 inara update cycles Error 429 occurred. I read in this case Inara is polled too often.

Inara website blocks and gives feedback:
"Please no mass site scraping by using scripts and similar, that includes an insane amount of page reloads within a very short time period. Thank you. If you believe this is an error, please try it again later or let me know... :)"

### To Reproduce
**Version**: Elite Dangerous Carrier Trader 2.2.0.1
**Steps to reproduce the behavior**:
1. delete the old database and all data. 
2. download and install EDCT 2.2.0.1 
3. start it. 
4. After progress 40/166 or near that amount it will trigger an inara block due to too many page reloads.

### Expected behavior
EDCT should slowly fill it's database in a pace that mimics an inara website user without triggering the mass site scraping detection.

### Screenshots
no need

### Additional context
none

**Comment by Fi0x** [comment]
Sadly inara changed the way it decides if you make too many requests. I couldn't find a way to prevent this from happening yet. But if you wait for all the commodities to finish loading, the tool should work (some commodities might not show up since they have no database entries, but if you keep the tool running during your game-time, it should get information for the most frequent visited stations via the EDDN).

**Comment by rucomania** [comment]
hi Fi0x,
After having your EDCT tool open during the night while sleeping, it seems it's working now. No errors after 2-3 hours running (as it seems checking the logs).
About 10 hours later it has 1559 systems, 10 distances, 826 stations, 236 commodities, 44070 export / 87549 import prices in the database.
It might be an idea to inform users of EDCT on a first run to keep the tool open for 3 hours and expect inara website blocks. After that it should go smoothly.
This ticket can be closed, since inara seems the culprit.
Thanks for your reaction and actions :)

**Comment by Fi0x** [comment]
Thank you for so much patience! I'll probably add your results to the wiki to inform users about the long waiting time.
