### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by JCalebBR** [Fi0x/EDCT#78]
### Is your feature request related to a problem? Please describe.
Currently Linux users would need to run edctsetup.exe via ED's wineprefix alongside the game, this already adds complexity when you have other tools like ED:MC for one. 

### Describe the solution you'd like
Would it be feasible to provide a .jar version? since then we would be able to run it natively (the application doesn't seem to have any game interaction, just api calls?)

### Describe alternatives you've considered
It currently launches with wine but the fonts and texts look wrong, background colour as well

**Comment by Fi0x** [comment]
I'll probably include a .jar in the next release. Didn't think of that :)

**Comment by JCalebBR** [comment]
Nice, looking forward to it. 
In the mean time, do you have any instructions on how I could do the build for the .jar?, If it's all possible in the current state

**Comment by Fi0x** [comment]
It should be possible to clone the repo and get all required dependencies via maven. Depending on your IDE you can compile the tool into a .jar like any other program

**Comment by JCalebBR** [comment]
Not familiar with maven or java, so please correct me if I'm wrong.
I got it to build successfully with `mvn clean package` though the jar wont run, I ran it with `java -jar FILENAME.jar` and just outputs `[2021/11/18 19:32:38] [INF] [---] DEBUG-MODE: false` and then exits, doesn't matter if I run `EliteDangerousCarrierTrader-1.6.9.8-jar-with-dependencies.jar` or `EliteDangerousCarrierTrader-1.6.9.8.jar`
Any thoughts?

**Comment by Fi0x** [comment]
In pom.xml, try to comment out line 115  and enable line 116. It's just below a TODO.
That should allow the jar to use your installed java version.

**Comment by JCalebBR** [comment]
I tried that, no luck still.

**Comment by Fi0x** [comment]
Do you have an IDE installed to test it?

**Comment by JCalebBR** [comment]
I only have VSCode available, what would be required for me to do?

**Comment by Fi0x** [comment]
Could you please try to run the tool inside VSCode?

That will probably not work, but this way you should get an exception in the VSCode-Console. Please send me that exception so I can work on it.

**Comment by Fi0x** [comment]
I added the .jar in the latest release
