### ISSUE TITLE
Stays forever in "Updating... Updated.... Updating...."

### ISSUE THREAD

**Issue by Selpheed** [Fi0x/EDCT#94]
### Describe the bug

Here it stopped working, it stays forever in "Updating... Updated.... Updating...."

### To Reproduce
**Version**: ...
**Steps to reproduce the behavior**:
1. ...

### Expected behavior
...

### Additional context
...

**Comment by Fi0x** [comment]
Hi, it's supposed to do that.
After a few seconds it should fetch new data from inara for the least recently updated commodity. In this state it says updating.
When the commodity is updated in the local database, it changes to updated. After a few more seconds it does the same for the next least recently updated commodity.

**Comment by JEricEaton** [comment]
I have experienced this same bug. After initial install and run, I have waited several hours and the screen continues to say:
Updating...
Storing EDDN information...

There is no additional information shown on the screen. It seems like it is stuck forever in loading and there is no way to determine progress or if there is an error.

**Comment by kdog0598** [comment]
How long should this updating take? I've left it to run overnight (8-9 hours) and it still just says "Updating..." and "Storing EDDN information..."

**Comment by Fi0x** [comment]
This bug was caused by the inara website that changed its layout. Since 2.0.0.0 this is fixed.

**Comment by 534n5mith** [comment]
Is this bug back? I am running 2.2.0.0 let it run for hours and no additional information is shown.

**Comment by Fi0x** [comment]
The bug shouldn't be there anymore, but it might be caused by some connection problems.
Can you please attach your log-file? That way I should be able to pinpoint the problem.
Your Log should be located in C:\Users\USERNAME\AppData\Roaming\EDCT\Logs

**Comment by rucomania** [comment]
I can confirm that in version 2.2.0.0 (downloaded and installed today and deleted the old database with all old files in my Windows10 profile) the updating (inara) keeps on spinning after 1 hour. Only 541 systems in the database, but NO distances, stations, commodities, export/import prices. If i use DB Browser for SQLite only the Systems table is filled with the stated 541 systems (all fields are filled with data). While the updating status is still running, each few seconds a new system is added to the table. But no other information in other tables are filled. What to do? Wait for a fix?

**Comment by rucomania** [comment]
I restarted EDCT and it continues the same process by filling the Systems table with a new solar system every few seconds. Nothing else happens.

**Comment by 534n5mith** [comment]
> The bug shouldn't be there anymore, but it might be caused by some connection problems. Can you please attach your log-file? That way I should be able to pinpoint the problem. Your Log should be located in C:\Users\USERNAME\AppData\Roaming\EDCT\Logs

Currently this folder is empty. I will run the tool for a while today to see if I can get any logs generated. Thanks for taking the time to look into this for everyone!

**Comment by rucomania** [comment]
My log was empty and my conbection as a hosting party is fine.Met vriendelijke groet,J. MenkemaOp 24 jan. 2023 om 16:28 heeft 534n5mith ***@***.***> het volgende geschreven:﻿

The bug shouldn't be there anymore, but it might be caused by some connection problems. Can you please attach your log-file? That way I should be able to pinpoint the problem. Your Log should be located in C:\Users\USERNAME\AppData\Roaming\EDCT\Logs

Currently this folder is empty. I will run the tool for a while today to see if I can get any logs generated. Thanks for taking the time to look into this for everyone!

**Comment by Fi0x** [comment]
Ok I think I know the source of the problem now. Inara updated the website layout again, which means that I have to adjust a few parts of my code.
I'll work on it as soon as possible.

Thank you all for bringing the issue to my attention!

**Comment by Fi0x** [comment]
In addition to the updated website-layout, inara now also checks for your browser-version. So I had to set one in the tool.

**Comment by Fi0x** [comment]
## Fixed in version 2.2.0.1
